"use client"

import type React from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { DollarSign, HardDrive, Copy, Settings, Globe, Zap } from "lucide-react"
import Link from "next/link"
import { motion } from "framer-motion"

export default function StorageKeepersPage() {
  return (
    <div className="container mx-auto py-12 px-4">
      <motion.h1
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-5xl font-extrabold text-center text-infinite-blue-700 mb-6 drop-shadow-lg"
      >
        Become an Infinite Storage Keeper
      </motion.h1>

      <motion.p
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1 }}
        className="text-xl text-center text-infinite-silver-700 max-w-3xl mx-auto mb-12"
      >
        Join our network and turn your unused storage space into a valuable asset. Contribute to a{" "}
        <strong>decentralized future</strong> and benefit directly from our revolutionary storage ecosystem.
      </motion.p>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <GlassmorphicCardKeeper
          icon={<DollarSign className="w-10 h-10 text-infinite-blue-500" />}
          title="Earn Real Money"
          description="Get compensated for providing reliable storage for encrypted files and for contributing to the overall network health and bandwidth. Multiple revenue streams available."
        />
        <GlassmorphicCardKeeper
          icon={<Copy className="w-10 h-10 text-infinite-blue-500" />}
          title="Access Public Content"
          description="For public files, you can copy and use the content you store. This unique incentive allows you to benefit directly from the valuable data you host."
        />
        <GlassmorphicCardKeeper
          icon={<HardDrive className="w-10 h-10 text-infinite-blue-500" />}
          title="Choose Your Categories"
          description="Decide what kind of content you want to store. Specialize in educational materials, games, media, or any category that interests you most."
        />
        <GlassmorphicCardKeeper
          icon={<Settings className="w-10 h-10 text-infinite-blue-500" />}
          title="Flexible Contribution"
          description="Set your preferred storage limit (e.g., 40GB) and choose whether to auto-accept new files or get notified for manual approval."
        />
        <GlassmorphicCardKeeper
          icon={<Globe className="w-10 h-10 text-infinite-blue-500" />}
          title="API Service Revenue"
          description="Benefit from a share of the revenue generated by developers integrating our storage network into their applications."
        />
        <GlassmorphicCardKeeper
          icon={<Zap className="w-10 h-10 text-infinite-blue-500" />}
          title="Marketplace Commissions"
          description="Earn a portion of the sales from content sold through the Infinite Content Marketplace, further diversifying your income streams."
        />
      </div>

      <motion.div
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.5 }}
        transition={{ duration: 0.6 }}
        className="text-center mt-12"
      >
        <Button
          className="relative overflow-hidden group text-lg px-8 py-4 rounded-full font-semibold
            bg-infinite-blue-500 text-white shadow-lg hover:bg-infinite-blue-600 transition-all duration-300
            backdrop-blur-sm border border-white/30
            before:absolute before:inset-0 before:bg-gradient-to-r before:from-white/20 before:to-transparent before:opacity-0 group-hover:before:opacity-100 before:transition-opacity before:duration-300
            "
          asChild
        >
          <Link href="/download" aria-label="Become a Storage Keeper and start earning">
            Join as a Keeper
          </Link>
        </Button>
      </motion.div>
    </div>
  )
}

interface GlassmorphicCardKeeperProps {
  icon: React.ReactNode
  title: string
  description: string
}

function GlassmorphicCardKeeper({ icon, title, description }: GlassmorphicCardKeeperProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.5 }}
      transition={{ duration: 0.6 }}
    >
      <Card
        className="relative overflow-hidden rounded-3xl shadow-2xl backdrop-blur-xl bg-white/25 border border-white/50
        before:absolute before:inset-0 before:rounded-3xl before:bg-gradient-to-br before:from-white/10 before:to-transparent before:z-[-1]
        after:absolute after:inset-0 before:rounded-3xl after:bg-gradient-to-tl after:from-white/10 after:to-transparent after:z-[-1]
        h-full
        "
      >
        <div
          className="absolute inset-0 rounded-3xl pointer-events-none
          shadow-[inset_0_0_15px_rgba(255,255,255,0.15),inset_0_0_30px_rgba(0,0,0,0.1)]
          border-[1px] border-white/60
        "
        ></div>
        <CardHeader className="flex flex-col items-center text-center p-6 relative z-10">
          {icon}
          <CardTitle className="mt-4 text-2xl font-bold text-infinite-blue-700">{title}</CardTitle>
        </CardHeader>
        <CardContent className="text-center text-infinite-silver-700 p-6 pt-0 relative z-10">
          <p>{description}</p>
        </CardContent>
      </Card>
    </motion.div>
  )
}
